#=
    Green identity tests for `bdim_correction` in single and double precision.
=#

using Test
using LinearAlgebra
using Random
using StaticArrays
using Inti

Random.seed!(1)

scalar_type(T) = T <: SMatrix ? eltype(T) : T

function test_bdim_green_identity(op, ::Type{Tp}; dim, meshsize, qorder, rtol1, rtol2) where {Tp}
    Inti.clear_entities!()
    Γ = if dim == 2
        Inti.parametric_curve(t -> SVector(cos(t), sin(t)), 0.0, 2π) |> Inti.Domain
    else
        Inti.boundary(Inti.ellipsoid() |> Inti.Domain)
    end
    msh = Inti.meshgen(Γ; meshsize, T = Tp)
    quad = Inti.Quadrature(view(msh, Γ); qorder)
    # interior solution generated by a point source outside the domain
    xs = ntuple(i -> Tp(3), dim)
    c = rand(Inti.default_density_eltype(op))
    γ₀u = map(q -> Inti.SingleLayerKernel(op)(q, xs) * c, quad)
    γ₁u = map(q -> Inti.AdjointDoubleLayerKernel(op)(q, xs) * c, quad)
    γ₀u_norm = norm(norm.(γ₀u, Inf), Inf)
    γ₁u_norm = norm(norm.(γ₁u, Inf), Inf)
    green_multiplier = fill(Inti._green_multiplier(:on), length(quad))
    σ = 1 // 2
    # single- and double-layer: S[γ₁u] - D[γ₀u] = σγ₀u on Γ
    Smat = Inti.assemble_matrix(Inti.IntegralOperator(Inti.SingleLayerKernel(op), quad))
    Dmat = Inti.assemble_matrix(Inti.IntegralOperator(Inti.DoubleLayerKernel(op), quad))
    @test real(scalar_type(eltype(Smat))) == Tp
    δS, δD = Inti.bdim_correction(op, quad, quad, Smat, Dmat; green_multiplier)
    @test eltype(δS) == eltype(Smat)
    e0 = norm((Smat * γ₁u - Dmat * γ₀u) - σ * γ₀u, Inf) / γ₀u_norm
    e1 = norm(((Smat + δS) * γ₁u - (Dmat + δD) * γ₀u) - σ * γ₀u, Inf) / γ₀u_norm
    @test e1 < rtol1
    @test e1 < e0
    # adjoint double-layer and hypersingular: K[γ₁u] - H[γ₀u] = σγ₁u on Γ
    Kmat = Inti.assemble_matrix(Inti.IntegralOperator(Inti.AdjointDoubleLayerKernel(op), quad))
    Hmat = Inti.assemble_matrix(Inti.IntegralOperator(Inti.HyperSingularKernel(op), quad))
    δK, δH = Inti.bdim_correction(
        op, quad, quad, Kmat, Hmat;
        green_multiplier, derivative = true,
    )
    e0 = norm((Kmat * γ₁u - Hmat * γ₀u) - σ * γ₁u, Inf) / γ₁u_norm
    e1 = norm(((Kmat + δK) * γ₁u - (Hmat + δH) * γ₀u) - σ * γ₁u, Inf) / γ₁u_norm
    return @test e1 < rtol2
end

@testset "bdim_correction $Tp" for Tp in (Float32, Float64)
    ops2 = (
        Inti.Laplace(; dim = 2),
        Inti.Helmholtz(; dim = 2, k = Tp(1.2)),
        Inti.Stokes(; dim = 2, μ = Tp(1.2)),
    )
    @testset "2d $(nameof(typeof(op)))" for op in ops2
        test_bdim_green_identity(
            op, Tp;
            dim = 2, meshsize = 0.2, qorder = 4, rtol1 = 1.0e-4, rtol2 = 1.0e-3,
        )
    end
    ops3 = (
        Inti.Laplace(; dim = 3),
        Inti.Helmholtz(; dim = 3, k = Tp(1.2)),
        Inti.Elastostatic(; dim = 3, μ = Tp(1), λ = Tp(1)),
    )
    @testset "3d $(nameof(typeof(op)))" for op in ops3
        test_bdim_green_identity(
            op, Tp;
            dim = 3, meshsize = 0.5, qorder = 4, rtol1 = 5.0e-3, rtol2 = 5.0e-2,
        )
    end
end
